Class Spain.FHIR.DTL.vR5.Model.Element.Appointment.recurrenceTemplate.yearlyTemplate Extends HS.FHIR.DTL.vR4.Model.Base.BackboneElement [ Not ProcedureBlock ]
{

/// integer
/// <p>
/// Recurs every nth year
Property yearInterval As %Integer(XMLNAME = "yearInterval", XMLPROJECTION = "ATTRIBUTE");

Parameter ELEMENTQUALIFIED = 1;

Parameter XMLNAME = "Appointment.recurrenceTemplate.yearlyTemplate";

Parameter XMLPROJECTION = "ELEMENT";

Parameter XMLSEQUENCE = 1;

Parameter XMLTYPE = "Appointment.recurrenceTemplate.yearlyTemplate";

}
