Class Spain.FHIR.DTL.vR5.Model.Datatype.Availability Extends HS.FHIR.DTL.vR4.Model.Base.Element
{

/// Available time
/// <p>
/// availableTime.
/// <p>
Property availableTime As list Of Spain.FHIR.DTL.vR5.Model.Element.Availability.availableTime(XMLNAME = "availableTime", XMLPROJECTION = "ELEMENT");

/// Available time
/// <p>
/// availableTime.
/// <p>
Property notAvailableTime As list Of Spain.FHIR.DTL.vR5.Model.Element.Availability.notAvailableTime(XMLNAME = "notAvailableTime", XMLPROJECTION = "ELEMENT");

Parameter ELEMENTQUALIFIED = 1;

Parameter XMLNAME = "Availability";

Parameter XMLPROJECTION = "ELEMENT";

Parameter XMLSEQUENCE = 1;

Parameter XMLTYPE = "Availability";

}
